# MockClaw Auto-Generated Mock Server
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from typing import Optional
import json

app = FastAPI(title='MockClaw Generated API')

@app.get('/health')
async def health():
    return {'status': 'OK', 'service': 'MockClaw'}

@app.get('/mockclaw/info')
async def info():
    return {'generator': 'MockClaw', 'version': '0.1.0'}

# Endpoint: GET /health

@app.get("/health")
async def mock_get__health():
    """Mock endpoint auto-generated by MockClaw"""
    return {"status": "OK"}


# Endpoint: GET /products

@app.get("/products")
async def mock_get__products():
    """Mock endpoint auto-generated by MockClaw"""
    return {"products": [{"id": "iphone15", "name": "iPhone 15 Pro", "price": 999.99}]}


# Endpoint: POST /cart/user123

@app.post("/cart/user123")
async def mock_post__cart_user123():
    """Mock endpoint auto-generated by MockClaw"""
    return {"message": "Added", "cart": []}


# Endpoint: POST /checkout

@app.post("/checkout")
async def mock_post__checkout():
    """Mock endpoint auto-generated by MockClaw"""
    return {"error": "COUPON_EXPIRED", "message": "Coupon 'EXPIRED2026' has expired"}

