# MockClaw Auto-Generated Mocks

from fastapi import FastAPI, APIRouter, Query, Path, HTTPException, status
from pydantic import BaseModel, Field
from typing import Optional, List, Any, Dict
import random
from faker import Faker
import json

fake = Faker()
app = FastAPI(title='MockClaw Generated API')
router = APIRouter()

# === Health Endpoints ===
@app.get("/health")
async def health_check():
    """Health check endpoint."""
    return {"status": "OK", "service": "MockClaw"}

@app.get("/mockclaw/info")
async def mockclaw_info():
    """MockClaw metadata endpoint."""
    return {
        "generator": "MockClaw",
        "version": "0.1.0",
        "endpoints": []
    }

# === Generated Endpoints ===

# Endpoint: /api/login
"""
Mock endpoint for POST /api/login
Auto-generated by MockClaw
"""
from fastapi import APIRouter, Query, Path, HTTPException, status
from pydantic import BaseModel, Field
from typing import Optional, List, Any
from faker import Faker
import random

fake = Faker()
router = APIRouter()

# Response Models
class MockResponse(BaseModel):
    data: Any = Field(default_factory=lambda: {
        "id": random.randint(1, 1000),
        "message": "mock response",
        "generated": True
    })


# Mock endpoint for POST /api/login
@app.post("/api/login")
async def mock_post_endpoint():
    """
    Mock endpoint auto-generated by MockClaw
    """
    # Check for error simulation
    if status_param := "error":
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail={"error": "Simulated error response", "status": "error"}
        )
    
    # Generate mock response data
    mock_data = {
    "token": "mock_jwt_token",
    "user": {
        "id": 1,
        "username": "testuser",
        "email": "test@example.com"
    }
}
    
    return MockResponse(data=mock_data)


# Endpoint: /api/users/{id}
"""
Mock endpoint for GET /api/users/{id}
Auto-generated by MockClaw
"""
from fastapi import APIRouter, Query, Path, HTTPException, status
from pydantic import BaseModel, Field
from typing import Optional, List, Any
from faker import Faker
import random

fake = Faker()
router = APIRouter()

# Response Models
class MockResponse(BaseModel):
    data: Any = Field(default_factory=lambda: {
        "id": random.randint(1, 1000),
        "message": "mock response",
        "generated": True
    })


# Mock endpoint for GET /api/users/{id}
@app.get("/api/users/{id}")
async def mock_get_endpoint():
    """
    Mock endpoint auto-generated by MockClaw
    """
    # Check for error simulation
    if status_param := "error":
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail={"error": "Simulated error response", "status": "error"}
        )
    
    # Generate mock response data
    mock_data = {
    "error": "Database connection failed",
    "code": "ERR_DB_CONNECTION"
}
    
    return MockResponse(data=mock_data)

