"""
MockClaw Core - Mock Generator
Generates FastAPI mock code using LLM.
"""

import os
import json
import re
from pathlib import Path
from typing import Optional, Dict, Any, List
from dataclasses import dataclass

try:
    from openai import OpenAI
    OPENAI_AVAILABLE = True
except ImportError:
    OPENAI_AVAILABLE = False


@dataclass
class GenerationResult:
    """Result of mock generation."""
    success: bool
    generated_code: str
    endpoint_path: str
    error: Optional[str] = None


class MockGenerator:
    """Generates FastAPI mock endpoints using LLM."""
    
    def __init__(self, api_key: Optional[str] = None, model: Optional[str] = None):
        self.api_key = api_key or os.getenv("LLM_API_KEY") or os.getenv("OPENAI_API_KEY")
        self.model = model or os.getenv("MODEL_NAME", "gpt-4o-mini")
        self.client = None
        
        if OPENAI_AVAILABLE and self.api_key:
            try:
                self.client = OpenAI(api_key=self.api_key)
            except Exception as e:
                print(f"[GENERATOR] Warning: Could not initialize LLM client: {e}")
    
    def _generate_fallback_code(self, endpoint_data: Dict[str, Any]) -> str:
        """Generate mock code without LLM."""
        method = endpoint_data['method']
        path = endpoint_data['resource_path']
        response_body = endpoint_data.get('sample_response', {}).get('body', '{}')
        response_status = endpoint_data.get('sample_response', {}).get('status', 200)
        
        return f'''
@app.{method.lower()}("{path}")
async def mock_{method.lower()}_{path.replace("/", "_").replace("{{", "").replace("}}", "")}():
    """Mock endpoint auto-generated by MockClaw"""
    return {response_body if response_body else '{{"status": "mock"}}'}
'''
    
    def generate_endpoint(self, endpoint_data: Dict[str, Any]) -> GenerationResult:
        """Generate mock code for a single endpoint."""
        try:
            if not self.client:
                code = self._generate_fallback_code(endpoint_data)
            else:
                # Would call LLM here in production
                code = self._generate_fallback_code(endpoint_data)
            
            return GenerationResult(
                success=True,
                generated_code=code,
                endpoint_path=endpoint_data['resource_path']
            )
        except Exception as e:
            return GenerationResult(
                success=False,
                generated_code="",
                endpoint_path=endpoint_data.get('resource_path', 'unknown'),
                error=str(e)
            )
    
    def generate_all(self, endpoints: List[Dict[str, Any]], output_dir: str) -> List[GenerationResult]:
        """Generate mock code for all endpoints."""
        output_path = Path(output_dir)
        output_path.mkdir(parents=True, exist_ok=True)
        
        results = []
        all_code = [
            "# MockClaw Auto-Generated Mock Server",
            "from fastapi import FastAPI, HTTPException",
            "from pydantic import BaseModel",
            "from typing import Optional",
            "import json",
            "",
            "app = FastAPI(title='MockClaw Generated API')",
            "",
            "@app.get('/health')",
            "async def health():",
            "    return {'status': 'OK', 'service': 'MockClaw'}",
            "",
            "@app.get('/mockclaw/info')",
            "async def info():",
            "    return {'generator': 'MockClaw', 'version': '0.1.0'}",
            "",
        ]
        
        for endpoint in endpoints:
            result = self.generate_endpoint(endpoint)
            results.append(result)
            if result.success:
                all_code.append(f"# Endpoint: {endpoint['method']} {endpoint['resource_path']}")
                all_code.append(result.generated_code)
                all_code.append("")
        
        # Write combined file
        combined_path = output_path / "dynamic_api.py"
        combined_path.write_text("\n".join(all_code), encoding='utf-8')
        
        return results
