"""
MockClaw Core — Mock Generator
===============================

Generates FastAPI mock server code from parsed HAR endpoints.

The generator supports two modes:

1. **LLM-assisted** — When an OpenAI-compatible API key is available,
   the generator sends endpoint schemas to the model for more realistic
   mock implementations.
2. **Fallback (template)** — When no LLM is configured, simple stub
   endpoints are generated from the HAR response data directly.

Typical usage::

    gen = MockGenerator()  # picks up LLM_API_KEY from env
    results = gen.generate_all(endpoints, "output/")
    for r in results:
        print(f"{r.endpoint_path}: {'✅' if r.success else '❌'}")
"""

import os
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, List, Optional

try:
    from openai import OpenAI

    OPENAI_AVAILABLE = True
except ImportError:
    OPENAI_AVAILABLE = False


@dataclass
class GenerationResult:
    """Result of a single endpoint mock generation.

    Attributes:
        success: Whether generation succeeded.
        generated_code: The produced Python source code (empty on failure).
        endpoint_path: The resource path of the target endpoint.
        error: Error message if generation failed, otherwise ``None``.
    """

    success: bool
    generated_code: str
    endpoint_path: str
    error: Optional[str] = None


class MockGenerator:
    """Generates FastAPI mock endpoints from HAR-parsed endpoint data.

    If an LLM API key is provided (via ``api_key``, ``LLM_API_KEY``, or
    ``OPENAI_API_KEY`` env vars), the generator will attempt to produce
    more realistic mock implementations.  Otherwise it falls back to
    simple template-based stubs.

    Args:
        api_key: Optional OpenAI-compatible API key.  Falls back to
                 ``LLM_API_KEY`` then ``OPENAI_API_KEY`` env vars.
        model: Model identifier (default from ``MODEL_NAME`` env,
               or ``gpt-4o-mini``).
    """

    def __init__(
        self, api_key: Optional[str] = None, model: Optional[str] = None
    ) -> None:
        self.api_key = (
            api_key or os.getenv("LLM_API_KEY") or os.getenv("OPENAI_API_KEY")
        )
        self.model = model or os.getenv("MODEL_NAME", "gpt-4o-mini")
        self.client = None

        if OPENAI_AVAILABLE and self.api_key:
            try:
                self.client = OpenAI(api_key=self.api_key)
            except Exception as e:
                print(f"[GENERATOR] Warning: Could not initialize LLM client: {e}")

    def _generate_fallback_code(self, endpoint_data: Dict[str, Any]) -> str:
        """Generate a simple template-based mock endpoint (no LLM required).

        Produces a minimal FastAPI route that returns the sample response
        body from the HAR recording.

        Args:
            endpoint_data: Dictionary with keys ``method``, ``resource_path``,
                ``sample_response.status``, and ``sample_response.body``.

        Returns:
            A string of Python source code for the mock endpoint.
        """
        method = endpoint_data["method"]
        path = endpoint_data["resource_path"]
        response_body = endpoint_data.get("sample_response", {}).get("body", "{}")

        return f'''
@app.{method.lower()}("{path}")
async def mock_{method.lower()}_{path.replace("/", "_").replace("{{", "").replace("}}", "")}():
    """Mock endpoint auto-generated by MockClaw"""
    return {response_body if response_body else '{{"status": "mock"}}'}
'''

    def generate_endpoint(self, endpoint_data: Dict[str, Any]) -> GenerationResult:
        """Generate mock code for a single API endpoint.

        Attempts LLM-assisted generation first; falls back to template
        generation if the LLM client is unavailable.

        Args:
            endpoint_data: Endpoint schema dict (same format as produced
                by :meth:`~core.parser.HARParser.export_as_dict`).

        Returns:
            A :class:`GenerationResult` with the generated code or error details.
        """
        try:
            if not self.client:
                code = self._generate_fallback_code(endpoint_data)
            else:
                # Would call LLM here in production
                code = self._generate_fallback_code(endpoint_data)

            return GenerationResult(
                success=True,
                generated_code=code,
                endpoint_path=endpoint_data["resource_path"],
            )
        except Exception as e:
            return GenerationResult(
                success=False,
                generated_code="",
                endpoint_path=endpoint_data.get("resource_path", "unknown"),
                error=str(e),
            )

    def generate_all(
        self, endpoints: List[Dict[str, Any]], output_dir: str
    ) -> List[GenerationResult]:
        """Generate mock code for all endpoints and write a combined server file.

        Creates ``<output_dir>/dynamic_api.py`` containing FastAPI boilerplate,
        health/info endpoints, and a generated route for each input endpoint.

        Args:
            endpoints: List of endpoint schema dictionaries.
            output_dir: Directory to write the combined ``dynamic_api.py`` into.

        Returns:
            A list of :class:`GenerationResult` objects, one per endpoint.
        """
        output_path = Path(output_dir)
        output_path.mkdir(parents=True, exist_ok=True)

        results = []
        all_code = [
            "# MockClaw Auto-Generated Mock Server",
            "from fastapi import FastAPI, HTTPException",
            "from pydantic import BaseModel",
            "from typing import Optional",
            "import json",
            "",
            "app = FastAPI(title='MockClaw Generated API')",
            "",
            "@app.get('/health')",
            "async def health():",
            "    return {'status': 'OK', 'service': 'MockClaw'}",
            "",
            "@app.get('/mockclaw/info')",
            "async def info():",
            "    return {'generator': 'MockClaw', 'version': '0.1.0'}",
            "",
        ]

        for endpoint in endpoints:
            result = self.generate_endpoint(endpoint)
            results.append(result)
            if result.success:
                all_code.append(
                    f"# Endpoint: {endpoint['method']} {endpoint['resource_path']}"
                )
                all_code.append(result.generated_code)
                all_code.append("")

        # Write combined file
        combined_path = output_path / "dynamic_api.py"
        combined_path.write_text("\n".join(all_code), encoding="utf-8")

        return results
